### PR TITLE
Removes content from master except README

### PR DESCRIPTION
**Pull request by vogella**
Ads all content has moved to the PDE repo, we should clean out master to
avoid anyone trying to work on this, because this person did not see the
information of the readme.

### CODE REVIEW

**Comment by vogella** [comment]
Hannes, WDYT?

**Review by HannesWell — APPROVED** [review]
> Hannes, WDYT?

Sounds good to me. 👍🏽

**Comment by HannesWell** [comment]
Just noticed that the `.github/workflows` and the `.gitignore` are still present. Just in case you really only want to keep the readme.

**Comment by vogella** [comment]
Noticed the same and push already another commit to remove them.

**Comment by HannesWell** [comment]
> Noticed the same and push already another commit to remove them.

Thanks!

**Pull request merged**
